### ISSUE TITLE
What's up with the weird CSS class suffixes?

### ISSUE THREAD

**Issue by cblaettl** [trendmicro-frontend/react-toggle-switch#2]
Many thanks.

**Comment by cheton** [comment]
It’s purposed for CSS modularization. If you want to do custom styling, you can copy the CSS file and modify it locally, or use styled-component to override default styles, like so:

```js
const StyledToggleSwitch = styled(ToggleSwitch)`
    && {
        [class*=“xxxx—”] {
            > a {
                cursor: pointer;
            }
        }
    }
`;
```

**Comment by cblaettl** [comment]
@cheton Cool, thanks for the quick response!
